.PHONY: run clean build
build:
	find ./*/ -type f -name Makefile -execdir make \;

run:
	find ./*/ -type f -name Makefile -execdir make run \;

clean:
	find ./*/ -type f -name Makefile -execdir make clean \;
