pub mod add;
pub mod axecutor;
pub mod errors;
pub mod execute;
pub mod flags;
mod integration_tests;
pub mod jmp;
pub mod lea;
mod macros;
pub mod memory;
pub mod mov;
pub mod operand;
pub mod pop;
pub mod push;
pub mod registers;
pub mod shl;
pub mod switch;
pub mod test;
mod tests;
pub mod xor;
