// THIS FILE IS AUTOGENERATED, DO NOT EDIT
// You can regenerate it using `make switch` after creating a new instruction file with `python3 generate.py <mneumonic>`

use super::{axecutor::Axecutor, errors::AxError};
use iced_x86::{Instruction, Mnemonic::*};

impl Axecutor {
    pub fn switch_instruction_mnemonic(&mut self, i: Instruction) -> Result<(), AxError> {
        match i.mnemonic() {
            Add => self.mnemonic_add(i),
            Cmp => self.mnemonic_cmp(i),
            Jmp => self.mnemonic_jmp(i),
            Lea => self.mnemonic_lea(i),
            Mov => self.mnemonic_mov(i),
            Nop => self.mnemonic_nop(i),
            Pop => self.mnemonic_pop(i),
            Push => self.mnemonic_push(i),
            Shl => self.mnemonic_shl(i),
            Sub => self.mnemonic_sub(i),
            Test => self.mnemonic_test(i),
            Xor => self.mnemonic_xor(i),
            _ => Err(AxError::from(format!(
                "unimplemented mnemonic {:?}",
                i.mnemonic()
            ))),
        }
    }
}
